name = "kodo"

[namespace.service]

[namespace.service.new]
required = ["credential"]
optional = ["endpoint", "http_client_options", "pair_policy"]

[namespace.service.op.create]
required = ["location"]

[namespace.service.op.delete]
required = ["location"]

[namespace.service.op.get]
required = ["location"]

[namespace.storage.new]
required = ["name", "location", "endpoint"]
optional = ["work_dir"]

[namespace.storage.op.list]
optional = ["list_mode"]

[namespace.storage.op.read]
optional = ["offset", "io_callback", "size"]

[namespace.storage.op.write]
optional = ["content_md5", "content_type", "io_callback", "storage_class"]

[pairs.storage_class]
type = "int"

[infos.object.meta.storage-class]
type = "int"